## Preprocessing

In [49]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [50]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns= ['EIN', 'NAME'])
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [51]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [52]:
# Look at APPLICATION_TYPE value counts for binning
application_counts = application_df['APPLICATION_TYPE'].value_counts()
application_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [53]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace =  application_counts[application_counts < 200].index

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [54]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [55]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts = classification_counts[classification_counts > 1]
classification_counts

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [56]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = classification_counts[classification_counts <100].index

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
Other      643
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C1370        1
C1236        1
C2190        1
C4200        1
C5200        1
C1900        1
C2600        1
C1248        1
C6100        1
C1820        1
C1580        1
C2570        1
C1732        1
C3700        1
C2500        1
C1570        1
C1283        1
C2380        1
C1728        1
C2170        1
C4120        1
C8210        1
C4500        1
C1245        1
C2561        1
C2150        1
Name: count, dtype: int64

In [57]:
# Convert categorical data to numeric with `pd.get_dummies`
app_dummies_df = pd.get_dummies(application_df, dtype = int)
app_dummies_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [58]:
# Split our preprocessed data into our features and target arrays
y = app_dummies_df['IS_SUCCESSFUL']
X = app_dummies_df.drop (columns = 'IS_SUCCESSFUL')

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [59]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [60]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=80, activation="leaky_relu", input_dim=len(X_train_scaled[0])))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=60, activation="leaky_relu"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=40, activation="leaky_relu"))

# Fourd hidden layer
nn.add(tf.keras.layers.Dense(units=20, activation="leaky_relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_14 (Dense)            (None, 80)                6080

 dense_15 (Dense)            (None, 60)                4860

 dense_16 (Dense)            (None, 40)                2440

 dense_17 (Dense)            (None, 20)                820

 dense_18 (Dense)            (None, 1)                 21

=================================================================
Total params: 14221 (55.55 KB)
Trainable params: 14221 (55.55 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [61]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [62]:
# Train the model
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 3s 2ms/step - loss: 0.5691 - accuracy: 0.7215
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5528 - accuracy: 0.7290
Epoch 3/50
804/804 [==============================] - 4s 4ms/step - loss: 0.5499 - accuracy: 0.7304
Epoch 4/50
804/804 [==============================] - 6s 8ms/step - loss: 0.5480 - accuracy: 0.7324
Epoch 5/50
804/804 [==============================] - 5s 7ms/step - loss: 0.5479 - accuracy: 0.7334
Epoch 6/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5463 - accuracy: 0.7327
Epoch 7/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5455 - accuracy: 0.7342
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5448 - accuracy: 0.7329
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5446 - accuracy: 0.7343
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5437 - accuracy: 0.7345
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5438 - accuracy: 0.7362
Epoch 12/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5430 - accuracy: 0.7351
Epoch 13/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5426 - accuracy: 0.7356
Epoch 14/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5421 - accuracy: 0.7364
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5420 - accuracy: 0.7356
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5416 - accuracy: 0.7371
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5413 - accuracy: 0.7361
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5410 - accuracy: 0.7365
Epoch 19/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5406 - accuracy: 0.7358
Epoch 20/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5401 - accuracy: 0.7360
Epoch 21/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7364
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7367
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7367
Epoch 24/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5399 - accuracy: 0.7375
Epoch 25/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5389 - accuracy: 0.7374
Epoch 26/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5390 - accuracy: 0.7371
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7372
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7377
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7378
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5378 - accuracy: 0.7383
Epoch 31/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5379 - accuracy: 0.7378
Epoch 32/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5378 - accuracy: 0.7382
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5375 - accuracy: 0.7386
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5377 - accuracy: 0.7392
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7379
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5368 - accuracy: 0.7385
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7391
Epoch 38/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5363 - accuracy: 0.7387
Epoch 39/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5367 - accuracy: 0.7386
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5360 - accuracy: 0.7387
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7391
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7383
Epoch 43/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5364 - accuracy: 0.7385
Epoch 44/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5356 - accuracy: 0.7378
Epoch 45/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5361 - accuracy: 0.7390
Epoch 46/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7390
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5349 - accuracy: 0.7397
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5356 - accuracy: 0.7390
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7391
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5353 - accuracy: 0.7394

In [63]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5508 - accuracy: 0.7310 - 737ms/epoch - 3ms/step
Loss: 0.5508438348770142, Accuracy: 0.7309620976448059

In [64]:

from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [65]:
# Export our model to HDF5 file
nn.save("/content/gdrive/MyDrive/Colab_Notebooks/AlphabetSoupCharity_Optimization3.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(